name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - umi
          - cmi
          - cas
    steps:
      - name: Display Configuration
        run: |
          echo "Compiler Device:${device}"
        env:
          device: ${{ matrix.device }}
      - name: Display Configuration Second
        run: |
          echo "Compiler Device:${device}"
